GET HTTP://localhost:3001/test

###
GET HTTP://localhost:3001/user/book
###
GET HTTP://localhost:3001/admin/users
###
GET HTTP://localhost:3001/admin/subUsers

###
POST HTTP://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "Filip",
    "password": "password"
}

###
POST HTTP://localhost:3001/admin/book
Content-Type: application/json

{
    "date": "2023-09-06",
    "trainer": "Isac",
    "trainType": "Kondition",
    "hours": 3,
    "startTime": 9
}
###
POST HTTP://localhost:3001/user/book
Content-Type: application/json

{
    "username": "Isac",
    "bookingId": 1
}