GET HTTP://localhost:3001/test

###
GET HTTP://localhost:3001/user/book
###
GET HTTP://localhost:3001/admin/users
###
GET HTTP://localhost:3001/user/subscriptions?username=filip
###
GET HTTP://localhost:3001/admin/subUsers?bookingID=2
###
GET HTTP://localhost:3001/admin/subUsers

###
POST HTTP://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "Filip",
    "password": "password"
}

###
POST HTTP://localhost:3001/admin/book
Content-Type: application/json

{
    "date": "2023-09-09",
    "trainer": "Oscar",
    "trainType": "Armar",
    "hours": 3,
    "startTime": 8
}
###
POST HTTP://localhost:3001/user/book
Content-Type: application/json

{
    "username": "Isac",
    "bookingId": 1
}
###
DELETE HTTP://localhost:3001/user/book
Content-Type: application/json

{
    "username": "filip",
    "bookingId": 1
}

###
DELETE HTTP://localhost:3001/admin/unSubUser
Content-Type: application/json

{
    "userID": 2,
    "bookingID": 1
}
